baseURL = 'http://localhost:3000'
languageCode = 'en-uk'
title = 'Hey! Welcome to my space'
theme = 'hugo-theme-monochrome'
DefaultContentLanguage = "en"
sectionPagesMenu = "main"

[params]
    noindex = false
    footer = "Copyright © 2024 by Abhishek Chandrasekar"
    description = "What I do and like :D. Dive into my portfolio and discover my creative journey."
    dateFormat = "Jan 2, 2006"
    enable_collapsible_toc = true # default: false

[[param.syntax_highlight]]
  lib = "builtin" # "builtin" | "prism.js" (default: "builtin")
    [param.syntax_highlight.builtin]
    enable_code_copy = true # default: true

[menu]
  [[menu.navbar]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10 
  
  [[menu.navbar]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20 
  
  [[menu.navbar]]
    identifier = "projects & certifications"
    name = "Projects & Certifications"
    url = "/projects_and_certifications/"
    weight = 30 
  
  [[menu.navbar]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 40 
