baseURL = 'http://localhost:3000'
languageCode = 'en-uk'
title = 'Hello there!, Welcome to my Portfolio'
theme = 'risotto'
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
ignoreErrors = ["error-remote-getjson"]
sectionPagesMenu = "main"

[params]
noindex = false

[params.theme]
palette = "tokyo-night-dark"

# Sidebar: about/bio
[params.about]
title = "Portfolio"
description = "What I do and like, built with terminal ricing in mind :D"
# To change image
logo = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fa-brands fa-github"
title = "GitHub"
url = "https://github.com/joeroe/risotto"

[[params.socialLinks]]
icon = "fa-brands fa-linkedin"
title = "LinkedIn"
url = "https://linkedin.com"

[[params.socialLinks]]
icon = "fa-solid fa-envelope"
title = "Email"
url = "mailto:example@example.com"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 20
  
  [[menu.main]]
    identifier = "certifications"
    name = "Certifications"
    url = "/certifications/"
    weight = 20

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

#[markup]
#
#  # Table of contents
#  # Add toc = true to content front matter to enable
#  [markup.tableOfContents]
#    startLevel = 2
#    endLevel   = 3
#    ordered    = true
